# -*- fill-column: 34; -*-
:PROPERTIES:
:ID:       f6f7fb38-af97-45a8-8eee-fc2e8beb79a9
:END:
#+title: pedido

11 linhas

Meu amor,
Coloquei aqui algumas imagens para
relembrar grande parte dos
momentos que já passamos juntos
durante esses 4 anos e 8 meses.
Que esse seja só o começo da nossa
vida. Que venham muitos e muitos
mais.
Te amo muito


---
* Carta

Querida Evelise,

há muito tempo venho pensando em te enviar esta carta. O motivo exato você já
conhece :)

Nunca em minha vida pensaria que encontraria alguém como você: íntegra,
companheira, linda e ainda com um senso de humor assim como o meu.
Não estava a procura, mas o destino nos uniu. Hoje entendo como algo tão
improvável ainda é possível de acontecer. Apesar de morarmos longe ir nos
conhecer em um lugar mais longe ainda. Bem, felizmente esse encontro ocorreu e
minha vida ficou muito mais feliz.
Vira e mexe relembro dos momentos que passamos.
Tanto os bons e quanto os ruins. Todos eles nos fizeram crescer, e como.
-> Já
passamos por bons e mau bocados, e o mais importante, passamos por eles juntos.
Infelizmente nem tão perto quanto gostaríamos. Mas cada dia que passa, dúvidas
desaparecem e a certeza aumenta. A certeza de que quero passar
o resto de minha vida contigo, bem pertinho. E assim quero dar mas um passo para
que alcancemos nosso objetivo em comum, ficarmos pertinhos até ficarmos velinhos.
Muito obrigado por existir e ter entrado em minha vida e muito mais por querer
continuar nela.

Na alegria e na tristeza, TE AMO MUITO!!! <3
