:PROPERTIES:
:ID:       b0af54fe-6089-4efb-af65-49eb4b37e870
:END:
#+title: necsys2022 Reviewers
#+filetags: reviewers

- tags :: [[id:0b1c1c06-7780-4f9a-bace-6b0dd37cac05][NecSys 2022]]

* Comments

** Comments to author (Associate Editor)

This paper studies the defense mechanism against a form of
linear false data injection attack for the distributed
model prediction control. The problem is interesting.
However, there are still many aspects that need further
improvements, such as the contribution statements, clear
symbols and notations, evaluations, typo errors, and so on.

** Reviewer 1 ID 89
The proposed design is more complicated than the original
on in Eq. (5). For MPC, the online computation is
important. So how to evaluate the proposed one's
practicality?
** TODO [2/4] Reviewer 2 ID 91
This paper studies the problem of mitigating the malicious
attack among the agents in a resource-sharing-based
distributed model predictive control framework. An
Expectation-Maximization based mitigation method is
proposed to suppress the effect of attacks. However, the
contributions and motivation are not clear enough. The
symbol and notions still need further improvement. The
detailed comments are given as follows.

1. [ ] In the introduction, the main contributions of this work should be clearly provided such that the reviewer can quickly and accurately catch the key points.
2. [ ] There are many assumptions made in this paper, i.e., Assumptions 1-5, without justification. Especially, it is not clear why the authors consider a linear form of attack as (10) shows, which is given in Assumption 3.
3. [X] The symbols used in this paper are not standard, e.g., the colon after (1) should be the set operation $\in$.
4. [X] In the simulation part, it is odd that the description of the attack behavior is hardly mentioned. Therefore, the reviewer cannot draw the conclusion from the simulation results that the proposed method is effective in mitigating the effect of the attacks as (10) shows.
5. There are also some typo errors that should be further checked.

** TODO [7/7] Reviewer 3 ID 93 (from PDF)
This  paper  studies  the  defense  mechanism  against  a  form  of  false  data  injection  attack  for the distributed model prediction control (dMPC). A central coordinator responsible for allocating control resources to plants has to detect the “faked” demand from the distributed controllers and mitigate this negative effect.  Although the studied problem is interesting,  the readability of the paper needs to be improved, and the technical approaches and some of the assumptions need to be justified.  The main concerns are as follows.

1. several letters in the title may need to be capitalized.
2. there are too many symbols in the paper,  which affects negatively the readability.  A table that summarizes the key variables might be helpful.
3. it seems that constraint (3) needs to hold for all the look-ahead times.  However, it was not made dependent on j ∈ H explicitly.
4. [X] diin (5a) is confusing since it was not explained until later in the paper.
5. [X] the information flow between the coordinator and the MPCs in Fig.  1 should be reversed?
6. [X] it was claimed that “The approach presented in this paper does not depend on the choice ofthe control objective”.  However, it is not clear how the quadratic form in terms of the control input u can still be guaranteed when the control objective is not linear in u.
7. [X] it  is  not  clear  why  the  variables P’s  ands’s  are  indexed  sometimes  by  superscripts j and sometimes by n.  Do they represent the different things?
8. [X] it seems that j-zone and zone j represent different things?
9. [X] Assumption 5 is not clear.  Do all the constraints need to active?  Or only at least one of theconstraints needs to be active.  It is not clear why this is a reasonable assumption.
10. it seems that the authors focus on a specific k in section 3.3.  However, in Assumption 6, the statement regarding U(k) needs to hold for all k.  Why is this the case?
11. in  applying  the  EM  algorithm,  it  is  not  clear  where  the  randomness  comes  from.   All  the responses from the controllers are deterministic.
12. [X] typo:  “which correspond” should be “which corresponds”; “are constraint by”
