#+TITLE: Fondamenti di Automatica - networked control
#+ROAM_KEY: https://farina.faculty.polimi.it/NetCont.html
- tag :: [[file:20200608100448-networked_control.org][networked control]]
https://farina.faculty.polimi.it/NetCont.html

* Leitura
:PROPERTIES:
:ID:       400d8bf5-9cdd-4cd3-97e6-e31185f2e75c
:END:
-  R. J. Baillieul, P. J. Antsaklis. Control and communication challenges in networked real-time systems. Proceedings of the IEEE, 95 (1), pp. 9-28.
-  J. R. Moyne and D. M. Tilbury. The emergence of industrial control networks for manufacturing control, diagnostics, and safety data. Proceedings of the IEEE, 95 (1), pp. 29-47.
-  R. J. Baillieul,. Feedback coding for information-based control: operating near the data-rate limit. Proceedings of the IEEE Conference on Decision and Control, 2002, pp. 3229-3236.
-  W. Zhang, M. S. Branicky, S. M. Phillips. Stability of networked control systems. IEEE Control Systems Magazine, 2001, pp. 84-99.
-  J. P. Hespanha, P. Naghshtabrizi, Y. Xu. A survey of recent results in networked control systems. Proceedings of the IEEE, 95 (1), pp. 138-162.
-  J. Lunze. Feedback Control of Large-Scale Systems. Prentice Hall International Series in Systems and Control Engineering, 1992.
-  A. Zecevic, D. D. Siljak. Control of complex systems. Structural constraints and uncertainty. Springer, 2010.
